# Generated by Django 5.2.17 on 2026-10-03 12:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('default_reliability', models.CharField(choices=[('confirmed', 'confirmed'), ('open_data', 'open_data'), ('user_report', 'user_report')], max_length=20)),
                ('refresh_policy', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('unavailable', 'Niedostępne')], default='ok', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('museum', 'Muzea'), ('food', 'Gastronomia'), ('lodging', 'Noclegi'), ('toilet', 'Toalety'), ('office', 'Urzędy'), ('culture', 'Kultura'), ('transport', 'Transport'), ('other', 'Inne')], default='other', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('key_note', models.TextField(blank=True)),
                ('osm_type', models.CharField(blank=True, max_length=10)),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('is_sample', models.BooleanField(default=False, help_text='Fikcyjne dane demonstracyjne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('osm_id__isnull', False)), fields=('osm_type', 'osm_id'), name='unique_osm_object')],
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('value', models.JSONField()),
                ('reliability', models.CharField(choices=[('confirmed', 'confirmed'), ('open_data', 'open_data'), ('user_report', 'user_report')], max_length=20)),
                ('observed_at', models.DateField(help_text='Kiedy informacja została pozyskana lub ostatnio potwierdzona')),
                ('note', models.TextField(blank=True)),
                ('is_sample', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='places.place')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='places.source')),
            ],
            options={
                'ordering': ['-observed_at', '-created_at'],
                'indexes': [models.Index(fields=['place', 'parameter'], name='places_fact_place_i_7fba78_idx')],
            },
        ),
    ]
