# Generated by Django 5.2.17 on 2026-10-03 12:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(unique=True)),
                ('kind', models.CharField(choices=[('kerb', 'Krawężnik'), ('crossing', 'Przejście')], max_length=16)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('tags', models.JSONField(default=dict)),
                ('observed_at', models.DateField(blank=True, null=True)),
                ('is_sample', models.BooleanField(default=False, help_text='Przykładowe dane demonstracyjne')),
            ],
        ),
    ]
